# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jwoschitz/kylo-hdp-sandbox-0.8.1"

  # flexible range to be able to expose several servers, primary use case relies on 9123
  for p in 9123..9133
    config.vm.network "forwarded_port", guest: p, host: p
  end

  config.vm.network "forwarded_port", guest: 5000, host: 5000, id: "Flask web application"

  config.vm.provision "file", source: "resources", destination: "resources"

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y git
    yum install -y epel-release
    yum install -y python-pip
    pip install --upgrade pip
    pip install virtualenv

    mkdir /opt/image_recognition_service/
    mv ~/resources/app /opt/image_recognition_service/web

    chown nifi:nifi -R /opt/image_recognition_service/

    su nifi

    mkdir -p /opt/image_recognition_service/bin/
    mkdir -p /opt/image_recognition_service/tensorflow/
    mkdir /opt/image_recognition_service/web/logs

    git clone https://github.com/tensorflow/models.git /opt/image_recognition_service/tensorflow/models

    virtualenv /opt/image_recognition_service/tensorflow/models/.venv
    source /opt/image_recognition_service/tensorflow/models/.venv/bin/activate
    pip install --upgrade tensorflow
    # invoke script one time to dynamically pull dependencies
    python /opt/image_recognition_service/tensorflow/models/tutorials/image/imagenet/classify_image.py
    deactivate

    echo "#!/bin/bash" > /opt/image_recognition_service/bin/classify_image.sh
    echo 'source /opt/image_recognition_service/tensorflow/models/.venv/bin/activate && python /opt/image_recognition_service/tensorflow/models/tutorials/image/imagenet/classify_image.py --image_file $1' >> /opt/image_recognition_service/bin/classify_image.sh
    chmod +x /opt/image_recognition_service/bin/classify_image.sh

    virtualenv /opt/image_recognition_service/web/.venv
    source /opt/image_recognition_service/web/.venv/bin/activate
    pip install Flask
    deactivate

    echo "#!/bin/bash" > /opt/image_recognition_service/bin/start_server.sh
    echo "source /opt/image_recognition_service/web/.venv/bin/activate && python /opt/image_recognition_service/web/app.py &> /opt/image_recognition_service/web/logs/app.log" >> /opt/image_recognition_service/bin/start_server.sh

    nohup /opt/image_recognition_service/bin/start_server.sh &

    exit

    sudo -u nifi /opt/image_recognition_service/bin/classify_image.sh /tmp/imagenet/cropped_panda.jpg
  SHELL
end
